services:
  # PC 1
  dev-a:
    image: ipfs/kubo:latest
    container_name: ipfs-pc-1
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
    volumes:
      - ./data/dev-a:/data/ipfs
      - .:/home/project
      - ./init-config.sh:/container-init.d/001-init-config.sh:ro
    environment:
      - IPFS_PROFILE=server

  # PC 2
  dev-b:
    image: ipfs/kubo:latest
    container_name: ipfs-pc-2
    ports:
      - "5002:5001"
      - "8081:8080"
      - "4002:4001"
    volumes:
      - ./data/dev-b:/data/ipfs
      - .:/home/project
      - ./init-config.sh:/container-init.d/001-init-config.sh:ro
    environment:
      - IPFS_PROFILE=server